<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net472;net10.0-windows</TargetFrameworks>
    <AssemblyName>NuGetAudit.Presentation</AssemblyName>
    <RootNamespace>NuGetAudit.Presentation</RootNamespace>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NuGetAudit.DbUtilities\NuGetAudit.DbUtilities.csproj" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.5" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3856.49" />
    <PackageReference Include="NuGet.Frameworks" Version="7.3.0" />
    <PackageReference Include="System.Text.Json" Version="10.0.5" />
  </ItemGroup>

</Project>
